### ISSUE TITLE
Completely not utf8 aware?

### ISSUE THREAD

**Issue by dmilith** [slash-hq/slash#24]
Each time I use Polish dialect chars I get some bogus "Å" instead of "ś" (same for any other utf8 inputs).

**Comment by glock45** [comment]
Fixed here: https://github.com/slash-hq/slash/commit/6a4a20fbde89e563bf595570d22f061dbda2c9ff

<img width="233" alt="zrzut ekranu 2019-02-05 o 23 06 09" src="https://user-images.githubusercontent.com/492449/52304165-bc28be80-299a-11e9-8544-56eb930956a7.png">
